server:
  port: 1111

spring:
  mail:
    host: smtp.qq.com
    username: @qq.com
    password: ???
    port: 587
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: false
            required: false
        debug: false

aliyun:
  dns:
    enable: false
    dns-config:
      - access-key-id: "???"
        access-key-secret: "???"
        domain-name: "???" #域名
        group-id: 123266 # 域名组id
        to-mail: "@qq.com" #邮件收件人

      - access-key-id: "???"
        access-key-secret: "???"
        domain-name: "???"
        group-id: 123787
        to-mail: "@qq.com"

thread-pool:
  core-pool-size: 5
  maximum-pool-size: 10
  keep-alive-time: 1000 # s
  queue-size: 100


logging:
  config: classpath:./logback-spring.xml
  file:
    path: /home/docker/my_spring/logs
  level:
    dao: info
